### ISSUE TITLE
Change docker-compose file with a docker hub image

### ISSUE THREAD

**Issue by StroescuTheo** [clglavan/private-notes#14]
Regarding the docker-compose file [here](https://github.com/clglavan/private-notes/blob/master/docker/docker-compose.yml#L6)
You could push the image to Docker Hub, and run docker-compose with a reference to that image, tagged with "latest".
So that a user can run the app using only the docker-compose file. It also helps with updating the app with a simple docker-compose pull command

**Comment by clglavan** [comment]
True, the current docker-compose is more or less intended for local development. More on this soon.

**Comment by clglavan** [comment]
The next step would be a github actions in this repo that would build that dockerfile.

**Comment by clglavan** [comment]
Please check: https://github.com/clglavan/private-notes/blob/master/docker/docker-compose-example.yml
Builds also happen on Tags if you want to pin a specific version.

Right now it only builds for linux/amd64, will provide a wider array soon.
