### ISSUE TITLE
[BugReport] Checkbox remains checked after refresh

### ISSUE THREAD

**Issue by StroescuTheo** [clglavan/private-notes#33]
## Describe the bug
If a checkbox is marked and the page refreshed, the checkbox remains active and still switches the textbox on and off, but in reverse order. The main functionality is kept only if the checkbox is marked.

## To Reproduce
1. Go to the main page
2. Check one of the checkboxes
3. Refresh the page
4. The checkbox is still marked but the textbox disappears
5. If unmarked the textbox appears

## Expected behavior
The checkbox should be unmarked upon refresh OR the textbox present if the checkbox remains marked after refresh

## Screenshots/Video
https://www.youtube.com/watch?v=2AysFc1esd4

## Desktop

- OS: Linux, Windows
- Browser: Firefox (Did not reproduce on Chrome)
- Version: 111.0 (64-bit)

## Mobile/Tablet

- Device: Samsung Android Phone
- Mobile Browser Firefox
- Version 111.0

## Additional context
Did not reproduce on Chrome

**Comment by clglavan** [comment]
Fixed with autocomplete="off" on the form
