### ISSUE TITLE
[BugReport] No data validation for textbox input on Firefox

### ISSUE THREAD

**Issue by StroescuTheo** [clglavan/private-notes#35]
## Describe the bug
On Firefox you can input anything in the textboxes. This includes letters and symbols in the "Custom expiration time" box

## To Reproduce
1. Go to the main page on Firefox
2. Check the Expiration time  checkbox
3. Input letters or symbols
4. The form still submits. I assume with default 60s?

## Expected behavior
The textbox should not allow for other characters beside digits.

## Screenshots/Video
![image](https://user-images.githubusercontent.com/15270005/227028373-caf00666-5d48-4b5d-b54a-03b51503a414.png)

## Desktop

- OS: Windows
- Browser: Firefox (Did not reproduce on Chrome)
- Version: 111.0 (64-bit)

## Mobile/Tablet

- Device: Samsung Android Phone
- Mobile Browser Firefox
- Version 111.0

## Additional context
A tooltip notifying you of bad inputs would be nice, but not necessary

**Comment by clglavan** [comment]
This is a firefox issue for not properly supporting basic html inputs, for now I will not bloat the javascript even more so nothing will be done.

Somehow firefox will send an empty field if it is not a proper number. This way in the backend the default is set.
