### ISSUE TITLE
[BugReport] Expiration time textbox allows floating point numbers

### ISSUE THREAD

**Issue by StroescuTheo** [clglavan/private-notes#37]
## Describe the bug
On Chrome, where data validation works fine( see [issue#35](https://github.com/clglavan/private-notes/issues/35)) you can still input the following characters: "-", "+", "e", "." 
I assume this is because of [floating point numbers](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number)

## To Reproduce
1. Go to the main page 
2. Check the Expiration time  checkbox
3. Input the mentioned symbols

## Expected behavior
The textbox should not allow for other characters beside digits.

## Screenshots/Video
![image](https://user-images.githubusercontent.com/15270005/227032341-76852ef3-8055-456e-afba-3cadc572ff5c.png)

**Comment by clglavan** [comment]
From what i tested on chrome, this scenario is caught by the validation. Clould you check again? The validation was to check on the client side if the input si lower than the MAXIMUM_EXPIRATION on the server, but somehow it implicitly tests for proper integers.

**Comment by StroescuTheo** [comment]
It's true that the validation catches "e" inputs.
But this still allows negative numbers to be sent, right? I assume that too is defaulted to 60s?

**Comment by clglavan** [comment]
True, I didn't check for the other characters, looks like with negative submits successfully. Might need a few more checks on the backend here:
https://github.com/clglavan/private-notes/blob/d3118544a8c50ff982b66e1d9e91daee2ee875e2/private_notes.go#L190-L216

**Comment by clglavan** [comment]
I've added a server side validation for floating inputs like . and negative numbers. Appending + for a number wont change anything if you so fancy.
